import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "../globals.css";
import { SigninButtonHome } from "../components/SigninButonHome";
import Link from "next/link";
import { Provider } from "../provider/SessionProvider";
import Nav from "../components/Nav";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function HomeLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <Provider>
          <header className="w-full bg-blue-400">
            <Nav/>
          </header>
          {children}
        </Provider>
      </body>
    </html>
  );
}
